### ISSUE TITLE
Error in Setup - Mac OS X (10.12.6) - g++-4.9 (4.9.4) via homebrew

### ISSUE THREAD

**Issue by suryaavala** [cjdb/project_template#3] opened 2017-08-02 05:46 UTC
I have done the default setup as per the project README

I couldn't pass the second test
`2 - test.demo.employee (Failed)`

Entire shell output can be found here:
https://pastebin.com/KkXDVEGM

A quick google search points me to the following answer:
https://stackoverflow.com/questions/39865367/warning-section-textcoal-nt-is-deprecate-since-updating-to-mac-osx-sierra

I was wondering if there is a work around? or Is it safe to ignore these warnings?

**Comment by cjdb** [comment] 2017-08-02 07:12
This looks like a duplicate of #1. Is your issue the same?

**Comment by suryaavala** [comment] 2017-08-02 13:47
Initially I thought it was the same issue as well. But installing gcc 4.9.2 did not solve the problem which is why I have opened this issue.

**Comment by suryaavala** [comment] 2017-08-02 14:00
The issue doesn't seem to be with gcc 4.9.4.
I have just installed 4.9.4 on my ubuntu machine, the project compiles and runs fine.
https://pastebin.com/pmir79Pd

`100% tests passed, 0 tests failed out of 2`

As pointed out here: http://techqa.info/programming/question/38193043/Disable-assembler-warning---section---TEXT---textcoal-nt-coalesced-pure-instructions-

Looks like the issue might with Mac's clang.

I can work on my ubuntu machine for now. So if nobody else faces this issue, maybe we can close this.

**Comment by allenlili** [comment] 2017-08-07 16:07
I have same issue on Mac OS X (10.12.6) - g++-4.9 (4.9.4) .

**Comment by cjdb** [comment] 2019-04-07 22:46
Significant revisions to this project have rendered this issue irrelevant.

**Closed as completed by cjdb** 2019-04-07 22:46 UTC
